# Generated by Django 4.1.5 on 2023-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('anh', models.ImageField(upload_to='media')),
                ('noidung', models.TextField(default='')),
                ('thoigian', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
