# Generated by Django 4.1.5 on 2023-05-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anh',
            field=models.ImageField(upload_to=''),
        ),
    ]
